### ISSUE TITLE
公式字体在服务器上的显示问题

### ISSUE THREAD

**Issue by Motues** [saicaca/fuwari#134]
公式在本地搭建的时候字体在是正常显示的，但是传到服务器上就会显示不对，如下所示：
![image](https://github.com/user-attachments/assets/db8ec1e3-ad58-45b6-af76-266563053e07)

在下面位置加上以下代码就好啦。
https://github.com/saicaca/fuwari/blob/f817e930ece65ead8c2438d9bc4de77a27ef5ec8/src/components/misc/Markdown.astro#L101
```css
  .katex {
    font-size: 1.1em
    font-family: "KaTeX_Main", Times New Roman, Times, serif;
  }
```

PS：发现只有像下面这样使用才会让公式换行居中，两个`$$`位于一行仍表现为`inline`形式。
```latex
$$
E=mc^2
$$
```
