### ISSUE TITLE
Wrong publication date despite correction

### ISSUE THREAD

**Issue by 4lt3rr** [saicaca/fuwari#310]
Hi I've recently seen a pretty annoying bug while I was blogging apparently I had put in my `.md` section like this:
```yml
---
title: "[HTB] - Execute"
published: 2025-30-01
description: "ROP with canary and stripped file"
image: ../../logo.jpg
tags:
- PWN
category: "Wargame"
draft: false
---
```

But somehow when I published it it was:

![Image](https://github.com/user-attachments/assets/57ad48d7-09f3-4c1e-aff6-6245d47309e1)
