### ISSUE TITLE
Establishing CI.

### ISSUE THREAD

**Issue by L4Ph** [saicaca/fuwari#372]
## Why
This is because it is necessary to always create a state where consistency is achieved using Linters and Formatters.

## What to do

Luckily, this project employs biome.
```yml
name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
```

By setting up GitHub Actions like these, you can ensure that your code is in a clean state at the time of the pull request.

By using `biome ci ./src --reporter=github`, you can display the results as a Pull Request message.
